services:
  postgres_db:
    image: postgres:latest
    container_name: go-db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: gopi-db
    ports:
      - "5432:5432"
    volumes:
      - ./config/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
  gopi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gopi-container
    restart: always
    ports:
      - "8080:8080"
    environment:
      DB_HOST: postgres_db
      DB_PORT: 5432
      DB_USER: user
      DB_PASS: pass
      DB_NAME: gopidb
      APP_ENV: development
      LOG_LEVEL: info
    depends_on:
      - postgres_db
volumes:
  postgres_db:
    driver: local
